module Contact {

  typedef DOMString AddressBookId;

  typedef DOMString ContactId;

  enum ContactTextFormat {"VCARD_21","VCARD_30"};

  [NoInterfaceObject] interface ContactManagerObject {
    readonly attribute ContactManager contact;
  };
  Tizen implements ContactManagerObject;

  [NoInterfaceObject] interface ContactManager {

    void getAddressBooks(AddressBookArraySuccessCallback successCallback,
                         optional ErrorCallback? errorCallback);

    AddressBook getDefaultAddressBook();

    AddressBook getAddressBook(AddressBookId id);
   };

  [NoInterfaceObject] interface AddressBook {

    readonly attribute AddressBookId id;

    readonly attribute DOMString name;
    
    readonly attribute boolean readOnly;
                             
    Contact get(ContactId id);
    
    void add(Contact contact);

    void addBatch(Contact[] contacts,
                  optional ContactArraySuccessCallback? successCallback,
                  optional ErrorCallback? errorCallback);

    void update(Contact contact);

    void updateBatch(Contact[] contacts,
                     optional SuccessCallback? successCallback,
                     optional ErrorCallback? errorCallback);

    void remove(ContactId id);

    void removeBatch(ContactId[] ids,
                     optional SuccessCallback? successCallback,
                     optional ErrorCallback? errorCallback);

    void find(ContactArraySuccessCallback successCallback,
              optional ErrorCallback? errorCallback,
              optional AbstractFilter? filter,
              optional SortMode? sortMode);

    DOMString[] getCategories();

    long addChangeListener(AddressBookChangeCallback successCallback,
                           optional ErrorCallback? errorCallback);

    void removeChangeListener(long watchId);
   };
   
  dictionary ContactInit {
    ContactName name;
    ContactAddress[] addresses;
    DOMString photoURI;
    ContactPhoneNumber[] phoneNumbers;
    ContactEmailAddress[] emails;
    Date birthday;
    ContactAnniversary[] anniversaries;
    ContactOrganization organization;
    DOMString note;
    ContactWebSite[] urls;
    boolean isFavorite;
    DOMString ringtoneURI;
    DOMString[] categories;
  };

  [Constructor(optional ContactInit? ContactInitDict),
   Constructor(DOMString stringRepresentation, ContactTextFormat format)]
  interface Contact {
    readonly attribute ContactId? id;

    readonly attribute AddressBookId? addressBookId;

    readonly attribute Date? lastUpdated;

    attribute ContactName? name;

    attribute ContactAccount? account;

    attribute ContactAddress[] addresses;

    attribute DOMString? photoURI;

    attribute ContactPhoneNumber[] phoneNumbers;

    attribute ContactEmailAddress[] emails;

    attribute Date? birthday;

    attribute ContactAnniversary[] anniversaries;

    attribute ContactOrganization? organization;

    attribute DOMString[] notes;

    attribute DOMString? note;

    attribute ContactWebSite[] urls;

    attribute boolean isFavorite;

    attribute DOMString? ringtoneURI;

    attribute DOMString[] categories;
    
     
    DOMString convertToString(ContactTextFormat format);
                              
    Contact clone();
  };
  
  [Constructor(AddressBookId addressBookId, ContactId contactId)]
  interface ContactRef {
    attribute AddressBookId addressBookId;
    
    attribute ContactId contactId;
  };
  
  dictionary ContactNameInit {
    DOMString prefix;
    DOMString firstName;
    DOMString middleName;
    DOMString lastName;
    DOMString[] nicknames;
    DOMString phoneticFirstName;
    DOMString phoneticLastName;
  };

  [Constructor(optional ContactNameInit? nameInitDict)]
  interface ContactName {
    attribute DOMString? prefix;

    attribute DOMString? firstName;

    attribute DOMString? middleName;

    attribute DOMString? lastName;

    attribute DOMString[] nicknames;

    attribute DOMString? phoneticName;

    attribute DOMString? phoneticFirstName;

    attribute DOMString? phoneticLastName;

    readonly attribute DOMString? displayName;
  };
  
  dictionary ContactOrganizationInit {
    DOMString name;
    DOMString department;
    DOMString title;
    DOMString role;
    DOMString logoURI;
  };

  [Constructor(optional ContactOrganizationInit? orgInitDict)]
  interface ContactOrganization {
    attribute DOMString? name;

    attribute DOMString? department;

    attribute DOMString? office;

    attribute DOMString? title;

    attribute DOMString? role;

    attribute DOMString? logoURI;
  };

  [Constructor(DOMString url, optional DOMString? type)]
  interface ContactWebSite
  {
    attribute DOMString url;

    attribute DOMString? type;
  };

  [Constructor(Date date, optional DOMString? label)]
  interface ContactAnniversary
  {
    attribute Date date;

    attribute DOMString? label;
  };

  [Constructor(AccountServiceId id, DOMString? contactURI)]
  interface ContactAccount {
    attribute AccountServiceId accountServiceId;

    attribute DOMString contactURI;
  };
  
  dictionary ContactAddressInit
  {
    DOMString country;
    DOMString region;
    DOMString city;
    DOMString streetAddress;
    DOMString additionalInformation;
    DOMString postalCode;
    DOMString[] types;
  };

  [Constructor(optional ContactAddressInit? addressInitDict)]
  interface ContactAddress
  {
    attribute DOMString? country;

    attribute DOMString? region;

    attribute DOMString? city;

    attribute DOMString? streetAddress;

    attribute DOMString? additionalInformation;

    attribute DOMString? postalCode;

    attribute DOMString[] types;
  };

  [Constructor(DOMString number, optional DOMString[]? types)]
  interface ContactPhoneNumber
  {
    attribute DOMString number;

    attribute DOMString[] types;
  };

  [Constructor(DOMString email, optional DOMString[]? types)]
  interface ContactEmailAddress
  {
    attribute DOMString email;

    attribute DOMString[] types;
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface ContactArraySuccessCallback {
    void onsuccess(Contact[] contacts);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface AddressBookArraySuccessCallback {
    void onsuccess(AddressBook[] addressbooks);
  };

  [Callback, NoInterfaceObject] interface AddressBookChangeCallback {
    void oncontactsadded(Contact[] contacts);

    void oncontactsupdated(Contact[] contacts);

    void oncontactsremoved(ContactId[] contactIds);
  };
};