module Download {

    enum DownloadState { "QUEUED", "DOWNLOADING", "PAUSED", "CANCELED", "COMPLETED", "FAILED" };

    [NoInterfaceObject] interface DownloadManagerObject {
        readonly attribute DownloadManager download;
    };

    Tizen implements DownloadManagerObject;

    [Constructor(DOMString url, optional DOMString? destination, optional DOMString? fileName)]
    interface DownloadRequest {
        attribute DOMString url;

        attribute DOMString? destination;

        attribute DOMString? fileName;
    };

   [NoInterfaceObject] interface DownloadManager {
       long start(DownloadRequest downloadRequest,
                    optional DownloadCallback? downloadCallback);

       void cancel(long downloadId);

       void pause(long downloadId);

       void resume(long downloadId);

       DownloadState getState(long downloadId);

       DownloadRequest getDownloadRequest(long downloadId);

       DOMString getMIMEType(long downloadId);

       void setListener(long downloadId, DownloadCallback downloadCallback);
   };

   [Callback, NoInterfaceObject] interface DownloadCallback {
       void onprogress(long downloadId, unsigned long long receivedSize, unsigned long long totalSize);

       void onpaused(long downloadId);

       void oncanceled(long downloadId);

       void oncompleted(long downloadId, DOMString fullPath);

       void onfailed(long downloadId, WebAPIError error);
   };
};

