module Download {

    enum DownloadState { "QUEUED", "DOWNLOADING", "PAUSED", "ABORTED", "COMPLETED", "FAILED" };

    [NoInterfaceObject] interface DownloadObject {
        readonly attribute DownloadManager download;
    };

    Tizen implements DownloadObject;

    [Constructor(DOMString url, optional DOMString? destination, optional DOMString? fileName)]
    interface URLDownload {
        attribute DOMString url;

        attribute DOMString? destination;

        attribute DOMString? fileName;
    };

   [NoInterfaceObject] interface DownloadManager {
       long start(URLDownload downloadObject,
                    optional DownloadCallback? downloadCallback);

       void abort(long downloadId);

       void pause(long downloadId);

       void resume(long downloadId);

       DownloadState getState(long downloadId);
   };

   [Callback, NoInterfaceObject] interface DownloadCallback {
       void onprogress(long downloadId, unsigned long long receivedSize, unsigned long long totalSize);

       void onpaused(long downloadId);

       void onaborted(long downloadId);

       void oncompleted(long downloadId, DOMString fileName);

       void onfailed(long downloadId, WebAPIError error);
   };
};