module Filesystem {
  enum FileMode { "r", "rw", "w", "a" };
  
  enum FileSystemStorageType { "INTERNAL", "EXTERNAL" };
  
  enum FileSystemStorageState { "MOUNTED", "REMOVED", "UNMOUNTABLE" };
  
  [NoInterfaceObject] interface FileSystemManagerObject {
    readonly attribute FileSystemManager filesystem;
  };
  Tizen implements FileSystemManagerObject;

  [NoInterfaceObject] interface FileSystemManager {
    readonly attribute long maxPathLength;

    void resolve(DOMString location,
                 FileSuccessCallback onsuccess,
                 optional ErrorCallback? onerror,
                 optional FileMode? mode);

    void getStorage(DOMString label,
                    FileSystemStorageSuccessCallback onsuccess,
                    optional ErrorCallback? onerror);

    void listStorages(FileSystemStorageArraySuccessCallback onsuccess,
                      optional ErrorCallback? onerror);

    long addStorageStateChangeListener(FileSystemStorageSuccessCallback onsuccess,
                                       optional ErrorCallback? onerror);

    void removeStorageStateChangeListener(long watchId);
  };

  [NoInterfaceObject] interface FileSystemStorage {
    readonly attribute DOMString label;

    readonly attribute FileSystemStorageType type;

    readonly attribute FileSystemStorageState state;
  };

  [NoInterfaceObject] interface File {
    readonly attribute File? parent;

    readonly attribute boolean readOnly;

    readonly attribute boolean isFile;

    readonly attribute boolean isDirectory;

    readonly attribute Date? created;

    readonly attribute Date? modified;

    readonly attribute DOMString path;

    readonly attribute DOMString name;

    readonly attribute DOMString fullPath;

    readonly attribute long fileSize;

    readonly attribute long length;

    DOMString toURI();

    void listFiles(FileArraySuccessCallback onsuccess,
                   optional ErrorCallback? onerror,
                   optional FileFilter? filter);

    void openStream(FileMode mode,
                    FileStreamSuccessCallback onsuccess,
                    optional ErrorCallback? onerror,
                    optional DOMString? encoding);

    void readAsText(FileStringSuccessCallback onsuccess,
                    optional ErrorCallback? onerror,
                    optional DOMString? encoding);

    void copyTo(DOMString originFilePath,
                DOMString destinationFilePath,
                boolean overwrite,
                optional SuccessCallback? onsuccess,
                optional ErrorCallback? onerror);

    void moveTo(DOMString originFilePath,
                DOMString destinationFilePath,
                boolean overwrite,
                optional SuccessCallback? onsuccess,
                optional ErrorCallback? onerror);

    File createDirectory(DOMString dirPath);

    File createFile(DOMString filePath);

    File resolve(DOMString filePath);

    void deleteDirectory(DOMString directory,
                         boolean recursive,
                         optional SuccessCallback? onsuccess,
                         optional ErrorCallback? onerror);

    void deleteFile(DOMString file,
                    optional SuccessCallback? onsuccess,
                    optional ErrorCallback? onerror);
  };


  dictionary FileFilter {
    DOMString name;

    Date startModified;

    Date endModified;

    Date startCreated;

    Date endCreated;
  };

  [NoInterfaceObject] interface FileStream {
    readonly attribute boolean eof;

    attribute long position;

    readonly attribute long bytesAvailable;

    void close();

    DOMString read(long charCount);

    octet[] readBytes(long byteCount);

    DOMString readBase64(long byteCount);

    void write(DOMString stringData);

    void writeBytes(octet[] byteData);

    void writeBase64(DOMString base64Data);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface FileSuccessCallback {
    void onsuccess(File file);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface FileSystemStorageArraySuccessCallback {
    void onsuccess(FileSystemStorage[] storages);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface FileSystemStorageSuccessCallback {
    void onsuccess(FileSystemStorage storage);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface FileStringSuccessCallback {
    void onsuccess(DOMString fileStr);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface FileStreamSuccessCallback {
    void onsuccess(FileStream filestream);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface FileArraySuccessCallback {
    void onsuccess(File[] files);
  };
};