module Messaging {

  [NoInterfaceObject] interface MessageManagerObject {
    readonly attribute Messaging messaging;
  };
  Tizen implements MessageManagerObject;

  enum MessageServiceTag {"messaging.sms", "messaging.mms", "messaging.email" };
  
  typedef DOMString MessageId;
  
  typedef DOMString MessageAttachmentId;

  typedef DOMString MessageConvId;

  typedef DOMString MessageFolderId;  

  [Constructor(MessageServiceTag type, optional MessageInit messageInitDict)]
  interface Message {

    readonly attribute MessageId? id;

    readonly attribute AccountServiceId? serviceId;

    readonly attribute MessageConvId? conversationId;

    readonly attribute MessageFolderId? folderId;

    readonly attribute MessageServiceTag type;

    readonly attribute Date? timestamp;

    readonly attribute DOMString? from;

    attribute DOMString[] to;

    attribute DOMString[] cc;

    attribute DOMString[] bcc;

    attribute MessageBody body;

    attribute boolean isRead;

    readonly attribute boolean hasAttachment;

    attribute boolean isHighPriority;

    attribute DOMString subject;

    attribute MessageId? inResponseTo;

    readonly attribute DOMString messageStatus;

    attribute MessageAttachment[] attachments;
  };
  dictionary MessageInit
  {

    DOMString subject;

    DOMString[] to;

    DOMString[] cc;

    DOMString[] bcc;

    DOMString plainBody;

    DOMString htmlBody;

    boolean isHighPriority;
  };

  [NoInterfaceObject] interface MessageBody {

    readonly attribute MessageId messageId;

    readonly attribute boolean loaded;

    attribute DOMString plainBody;

    attribute DOMString htmlBody;

    attribute MessageAttachment[] inlineAttachments;
  };

  [Constructor(DOMString filePath, optional DOMString mimeType)]
  interface MessageAttachment {

    readonly attribute MessageAttachmentId? id;

    readonly attribute MessageId? messageId;

    readonly attribute DOMString? mimeType;

    readonly attribute DOMString? filePath;
  };

  [NoInterfaceObject] interface Messaging {

    void getMessageServices(MessageServiceTag messageServiceType,
                            MessageServiceArraySuccessCallback successCallback,
                            optional ErrorCallback? errorCallback,
                            optional AccountServiceId? serviceId);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface MessageServiceArraySuccessCallback {

    void onsuccess(MessageService[] services);

  };


  [NoInterfaceObject] interface MessageService {

    readonly attribute AccountServiceId id;

    readonly attribute MessageServiceTag type;

    readonly attribute DOMString name;
                    
    void sendMessage(Message message,
                     optional MessageRecipientsCallback successCallback,
                     optional ErrorCallback? errorCallback);

    void loadMessageBody(Message message,
                         MessageBodySuccessCallback successCallback,
                         optional ErrorCallback? errorCallback);

    void loadMessageAttachment(MessageAttachment attachment,
                               MessageAttachmentSuccessCallback successCallback,
                               optional ErrorCallback? errorCallback);

    long sync(optional SuccessCallback? successCallback,
              optional ErrorCallback? errorCallback,
              optional unsigned long limit);

    long syncFolder(MessageFolder folder,
                    optional SuccessCallback? successCallback,
                    optional ErrorCallback? errorCallback,
                    optional unsigned long limit);

    void stopSync(long opId);

    readonly attribute MessageStorage messageStorage;
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface MessageRecipientsCallback {

    void onsuccess(DOMString[] recipients);

   };

  [Callback=FunctionOnly, NoInterfaceObject] interface MessageBodySuccessCallback {

     void onsuccess(Message message);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface MessageAttachmentSuccessCallback {

     void onsuccess(MessageAttachment attachment);
   };

  [NoInterfaceObject] interface MessageStorage {

    void addDraftMessage(Message message,
                         optional SuccessCallback? successCallback,
                         optional ErrorCallback? errorCallback);

    void findMessages(AbstractFilter filter,
                      MessageArraySuccessCallback successCallback,
                      optional ErrorCallback? errorCallback,
                      optional SortMode? sort,
                      optional unsigned long? limit,
                      optional unsigned long? offset);

    void removeMessages(Message[] messages,
                        optional SuccessCallback? successCallback,
                        optional ErrorCallback? errorCallback);

    void updateMessages(Message[] messages,
                        optional SuccessCallback? successCallback,
                        optional ErrorCallback? errorCallback);

    void findConversations(AbstractFilter filter,
                           MessageConversationArraySuccessCallback successCallback,
                           optional ErrorCallback? errorCallback,
                           optional SortMode? sort,
                           optional unsigned long? limit,
                           optional unsigned long offset);

    void removeConversations(MessageConversation[] conversations,
                             optional SuccessCallback? successCallback,
                             optional ErrorCallback? errorCallback);


    void findFolders(AbstractFilter filter,
                     MessageFolderArraySuccessCallback successCallback,
                     optional ErrorCallback? errorCallback);

    long addMessagesChangeListener(MessagesChangeCallback messagesChangeCallback,
                                   optional AbstractFilter filter);

    long addConversationsChangeListener(MessageConversationsChangeCallback conversationsChangeCallback,
                                        optional AbstractFilter filter);

    long addFoldersChangeListener(MessageFoldersChangeCallback foldersChangeCallback,
                                  optional AbstractFilter filter);

    void removeChangeListener(long watchId);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface MessageArraySuccessCallback {

    void onsuccess(Message[] messages);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface MessageConversationArraySuccessCallback {

    void onsuccess(MessageConversation[] conversations);
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface MessageFolderArraySuccessCallback {

    void onsuccess(MessageFolder[] folders);
  };

  [Callback, NoInterfaceObject] interface MessagesChangeCallback {

    void messagesadded(Message[] addedMessages);

    void messagesupdated(Message[] updatedMessages);

    void messagesremoved(Message[] removedMessages);
  };

  [Callback, NoInterfaceObject] interface MessageConversationsChangeCallback {

    void conversationsadded(MessageConversation[] addedConversations);

    void conversationsupdated(MessageConversation[] updatedConversations);

    void conversationsremoved(MessageConversation[] removedConversations);
  };

  [Callback, NoInterfaceObject] interface MessageFoldersChangeCallback {
 
    void foldersadded(MessageFolder[] addedFolders);

    void foldersupdated(MessageFolder[] updatedFolders);

    void foldersremoved(MessageFolder[] removedFolders);
  };

  [NoInterfaceObject] interface MessageConversation {

    readonly attribute MessageConvId id;

    readonly attribute MessageServiceTag type;

    readonly attribute Date timestamp;
     
    readonly attribute unsigned long messageCount;

    readonly attribute unsigned long unreadMessages;

    readonly attribute DOMString preview;

    readonly attribute DOMString subject;

    readonly attribute boolean isRead;

    readonly attribute DOMString from;

    readonly attribute DOMString[] to;

    readonly attribute DOMString[] cc;

    readonly attribute DOMString[] bcc;

    readonly attribute MessageId lastMessageId;
  };

  [NoInterfaceObject] interface MessageFolder {

    readonly attribute MessageFolderId id;

    readonly attribute MessageFolderId parentId;

    readonly attribute AccountServiceId serviceId;

    readonly attribute MessageServiceTag contentType;

    attribute DOMString name;

    readonly attribute DOMString path;

    readonly attribute DOMString type;

    attribute boolean synchronizable;
  };

};