module Power {

    enum PowerResource    { "DISPLAY" };

    enum PowerState { "DISPLAY_OFF", "DISPLAY_DIM", "DISPLAY_NORMAL", "DISPLAY_BRIGHT" };

    [NoInterfaceObject] interface PowerObject {
        readonly attribute PowerManager power;
    };
    Tizen implements PowerObject;

    [Constructor(PowerResource resource, PowerState state)] interface PowerStateRequest {
        attribute PowerResource resource;

        attribute PowerState    minimalState;
    };

   [NoInterfaceObject] interface PowerManager {
       void request(PowerStateRequest request,
                    optional SuccessCallback? successCallback,
                    optional ErrorCallback? errorCallback,
                    optional PowerStateChangeCallback? listener);

       void release(PowerResource resource);
   };

   [Callback=FunctionOnly, NoInterfaceObject] interface PowerStateChangeCallback {
       void onchanged(PowerResource resource,
                      PowerState actualState,
                      PowerState requestedState);
   };

};