module Power {

    enum PowerResource    { "SCREEN", "CPU" };

    enum PowerScreenState { "SCREEN_OFF", "SCREEN_DIM", "SCREEN_NORMAL", "SCREEN_BRIGHT" };

    enum PowerCpuState { "CPU_AWAKE" };

    typedef (PowerScreenState or PowerCpuState) PowerState;

    [NoInterfaceObject] interface PowerManagerObject {
        readonly attribute PowerManager power;
    };
    Tizen implements PowerManagerObject;

   [NoInterfaceObject] interface PowerManager {
       void request(PowerResource resource, PowerState state);

       void release(PowerResource resource);

       void setScreenStateChangeListener(ScreenStateChangeCallback listener);

       void unsetScreenStateChangeListener();

       double getScreenBrightness();

       void setScreenBrightness(double brightness);

       boolean isScreenOn();

       void restoreScreenBrightness();

       void turnScreenOn();

       void turnScreenOff();
   };

   [Callback=FunctionOnly, NoInterfaceObject] interface ScreenStateChangeCallback {
       void onchanged(PowerScreenState previousState, 
					  PowerScreenState changedState);
   };

};