module SystemSetting {

  [NoInterfaceObject] interface SystemSettingObject {
    readonly attribute SystemSettingManager systemsetting;
  };
    Tizen implements SystemSettingObject;

  enum SystemSettingType {"HOME_SCREEN", "LOCK_SCREEN", "INCOMING_CALL", "NOTIFICATION_EMAIL"};

  [NoInterfaceObject] interface SystemSettingManager {

     void setProperty(SystemSettingType type,
              DOMString value,
              SuccessCallback successCallback,
              optional ErrorCallback? errorCallback) raises (WebAPIException);

     void getProperty(SystemSettingType type,
              SystemSettingSuccessCallback successCallback,
              optional ErrorCallback? errorCallback) raises (WebAPIException);
     
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface SystemSettingSuccessCallback {
    void onsuccess(DOMString value);
  };

};