module SystemInfo {

  typedef DOMString PropertyId;

  enum SystemInfoNetworkType { "NONE", "2G", "2.5G", "3G", "4G", "WIFI", "ETHERNET", "UNKNOWN" };

  enum SystemInfosDeviceOrientationStatus { "portrait-primary", "portrait-secondary", "landscape-primary", "landscape-secondary" };

  [NoInterfaceObject] interface SystemInfoObject {
    readonly attribute SystemInfo systeminfo;
  };
  Tizen implements SystemInfoObject;

  [NoInterfaceObject] interface SystemInfo {

    boolean isSupported(PropertyId property);

    void getPropertyValue(PropertyId property,
                          SystemInfoPropertySuccessCallback successCallback,
                          optional ErrorCallback? errorCallback);

    long addPropertyValueChangeListener(PropertyId property,
                                        SystemInfoPropertySuccessCallback successCallback,
                                        optional ErrorCallback? errorCallback,
                                        optional SystemInfoOptions? options);

    void removePropertyValueChangeListener(long listenerID);
  };

  dictionary SystemInfoOptions {
    unsigned long timeout;

    double highThreshold;

    double lowThreshold;
  };

  [Callback=FunctionOnly, NoInterfaceObject] interface SystemInfoPropertySuccessCallback {
    void onsuccess(SystemInfoProperty prop);
  };

  [NoInterfaceObject] interface SystemInfoProperty {
  };

  [NoInterfaceObject] interface SystemInfoPower : SystemInfoProperty {
    readonly attribute double level;

    readonly attribute boolean isCharging;
  };

  [NoInterfaceObject] interface SystemInfoCpu : SystemInfoProperty {
    readonly attribute double load;
  };

  [NoInterfaceObject] interface SystemInfoStorage : SystemInfoProperty {
    readonly attribute SystemInfoStorageUnit[] units;
  };

  [NoInterfaceObject] interface SystemInfoStorageUnit : SystemInfoProperty {
    readonly attribute DOMString type;

    readonly attribute unsigned long capacity;

    readonly attribute unsigned long availableCapacity;

    readonly attribute boolean isRemoveable;
  };

  [NoInterfaceObject] interface SystemInfoDisplay : SystemInfoProperty {
    readonly attribute unsigned long resolutionWidth;

    readonly attribute unsigned long resolutionHeight;

    readonly attribute unsigned long dotsPerInchWidth;

    readonly attribute unsigned long dotsPerInchHeight;

    readonly attribute double physicalWidth;

    readonly attribute double physicalHeight;

    readonly attribute double brightness;
  };

  [NoInterfaceObject] interface SystemInfoDevice : SystemInfoProperty {
    readonly attribute DOMString imei;

    readonly attribute DOMString model;

    readonly attribute DOMString version;

    readonly attribute DOMString vendor;
  };

  [NoInterfaceObject] interface SystemInfoNetwork : SystemInfoProperty {

    readonly attribute SystemInfoNetworkType networkType;
  };

  [NoInterfaceObject] interface SystemInfoWifiNetwork : SystemInfoProperty {
    readonly attribute DOMString status;

    readonly attribute DOMString ssid;

    readonly attribute DOMString ipAddress;

    readonly attribute DOMString ipv6Address;

    readonly attribute double signalStrength;
  };

  [NoInterfaceObject] interface SystemInfoCellularNetwork : SystemInfoProperty {
    readonly attribute DOMString status;

    readonly attribute DOMString apn;

    readonly attribute DOMString ipAddress;

    readonly attribute DOMString ipv6Address;

    readonly attribute unsigned short mcc;

    readonly attribute unsigned short mnc;

    readonly attribute unsigned short cellId;

    readonly attribute unsigned short lac;

    readonly attribute boolean isRoaming;
  };

  [NoInterfaceObject] interface SystemInfoEthernetNetwork: SystemInfoProperty {
    readonly attribute DOMString status;

    readonly attribute DOMString ipAddress;

    readonly attribute DOMString ipv6Address;

    readonly attribute DOMString proxyAddress;

    readonly attribute DOMString macAddress;

    readonly attribute DOMString gateway;

    readonly attribute DOMString dns;

    readonly attribute DOMString subnetMask;
  };

  [NoInterfaceObject] interface SystemInfoSIM : SystemInfoProperty {

    readonly attribute DOMString operatorName;

    readonly attribute DOMString msisdn;

    readonly attribute DOMString iccid;

    readonly attribute unsigned short mcc;

    readonly attribute unsigned short mnc;

    readonly attribute DOMString msin;

    readonly attribute DOMString spn;
  };

  [NoInterfaceObject] interface SystemInfoDeviceOrientation : SystemInfoProperty {

    readonly attribute  SystemInfosDeviceOrientationStatus status;
  };

};