// Wraps Tizen module "Bluetooth".

define(['Ti/_/lang', 'Ti/_/Evented', 'Tizen/_/Bluetooth/BluetoothAdapter'], function(lang, Evented, BluetoothAdapter) {

	return lang.mixProps(require.mix({}, Evented), {

		_wrap: function(object) {
			// Wrap the object (create a Titanium wrapped object out of a native Tizen object).

			if (object.toString() === '[object BluetoothAdapter]') {
				return new BluetoothAdapter(object);
			}
			else {
				throw new Error('Object of unknown type');
			}
		},

		getDefaultAdapter: function() {
			try {
				return this._wrap(tizen.bluetooth.getDefaultAdapter());
			} catch (e) {
				console.error(e.message);
			}
		},

		constants: {
			BLUETOOTH_SECURITY_LEVEL_LOW: 'LOW',
			BLUETOOTH_SECURITY_LEVEL_MEDIUM: 'MEDIUM',
			BLUETOOTH_SECURITY_LEVEL_HIGH: 'HIGH',
			BLUETOOTH_SOCKET_TYPE_RFCOMM: 'RFCOMM',
			BLUETOOTH_SOCKET_TYPE_L2CAP: 'L2CAP',
			BLUETOOTH_SOCKET_STATE_CLOSED: 'CLOSED',
			BLUETOOTH_SOCKET_STATE_OPEN: 'OPEN',
			// from BluetoothClassDeviceMajor of Tizen
			BLUETOOTH_CLASS_DEVICE_MAJOR_MISC: 0x00,
			BLUETOOTH_CLASS_DEVICE_MAJOR_COMPUTER: 0x01,
			BLUETOOTH_CLASS_DEVICE_MAJOR_PHONE: 0x02,
			BLUETOOTH_CLASS_DEVICE_MAJOR_NETWORK: 0x03,
			BLUETOOTH_CLASS_DEVICE_MAJOR_AUDIO_VIDEO: 0x04,
			BLUETOOTH_CLASS_DEVICE_MAJOR_PERIPHERAL: 0x05,
			BLUETOOTH_CLASS_DEVICE_MAJOR_IMAGING: 0x06,
			BLUETOOTH_CLASS_DEVICE_MAJOR_WEARABLE: 0x07,
			BLUETOOTH_CLASS_DEVICE_MAJOR_TOY: 0x08,
			BLUETOOTH_CLASS_DEVICE_MAJOR_HEALTH: 0x09,
			BLUETOOTH_CLASS_DEVICE_MAJOR_UNCATEGORIZED: 0x1F,
			// from BluetoothClassDeviceMinor of Tizen
			BLUETOOTH_CLASS_DEVICE_MINOR_COMPUTER_UNCATEGORIZED: 0x00,
			BLUETOOTH_CLASS_DEVICE_MINOR_COMPUTER_DESKTOP: 0x01,
			BLUETOOTH_CLASS_DEVICE_MINOR_COMPUTER_SERVER: 0x02,
			BLUETOOTH_CLASS_DEVICE_MINOR_COMPUTER_LAPTOP: 0x03,
			BLUETOOTH_CLASS_DEVICE_MINOR_COMPUTER_HANDHELD_PC_OR_PDA: 0x04,
			BLUETOOTH_CLASS_DEVICE_MINOR_COMPUTER_PALM_PC_OR_PDA: 0x05,
			BLUETOOTH_CLASS_DEVICE_MINOR_COMPUTER_WEARABLE: 0x06,
			BLUETOOTH_CLASS_DEVICE_MINOR_PHONE_UNCATEGORIZED: 0x00,
			BLUETOOTH_CLASS_DEVICE_MINOR_PHONE_CELLULAR: 0x01,
			BLUETOOTH_CLASS_DEVICE_MINOR_PHONE_CORDLESS: 0x02,
			BLUETOOTH_CLASS_DEVICE_MINOR_PHONE_SMARTPHONE: 0x03,
			BLUETOOTH_CLASS_DEVICE_MINOR_PHONE_MODEM_OR_GATEWAY: 0x04,
			BLUETOOTH_CLASS_DEVICE_MINOR_PHONE_ISDN: 0x05,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_UNRECOGNIZED: 0x00,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_WEARABLE_HEADSET: 0x01,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_HANDSFREE: 0x02,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_MICROPHONE: 0x04,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_LOUDSPEAKER: 0x05,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_HEADPHONES: 0x06,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_PORTABLE_AUDIO: 0x07,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_CAR_AUDIO: 0x08,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_SETTOP_BOX: 0x09,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_HIFI: 0x0a,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_VCR: 0x0b,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_VIDEO_CAMERA: 0x0c,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_CAMCORDER: 0x0d,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_MONITOR: 0x0e,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_DISPLAY_AND_LOUDSPEAKER: 0x0f,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_VIDEO_CONFERENCING: 0x10,
			BLUETOOTH_CLASS_DEVICE_MINOR_AV_GAMING_TOY: 0x12,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_UNCATEGORIZED: 0,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_KEYBOARD: 0x10,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_POINTING_DEVICE: 0x20,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_KEYBOARD_AND_POINTING_DEVICE: 0x30,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_JOYSTICK: 0x01,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_GAMEPAD: 0x02,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_REMOTE_CONTROL: 0x03,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_SENSING_DEVICE: 0x04,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_DEGITIZER_TABLET: 0x05,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_CARD_READER: 0x06,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_DIGITAL_PEN: 0x07,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_HANDHELD_SCANNER: 0x08,
			BLUETOOTH_CLASS_DEVICE_MINOR_PERIPHERAL_HANDHELD_INPUT_DEVICE: 0x09,
			BLUETOOTH_CLASS_DEVICE_MINOR_IMAGING_UNCATEGORIZED: 0x00,
			BLUETOOTH_CLASS_DEVICE_MINOR_IMAGING_DISPLAY: 0x04,
			BLUETOOTH_CLASS_DEVICE_MINOR_IMAGING_CAMERA: 0x08,
			BLUETOOTH_CLASS_DEVICE_MINOR_IMAGING_SCANNER: 0x10,
			BLUETOOTH_CLASS_DEVICE_MINOR_IMAGING_PRINTER: 0x20,
			BLUETOOTH_CLASS_DEVICE_MINOR_WEARABLE_WRITST_WATCH: 0x01,
			BLUETOOTH_CLASS_DEVICE_MINOR_WEARABLE_PAGER: 0x02,
			BLUETOOTH_CLASS_DEVICE_MINOR_WEARABLE_JACKET: 0x03,
			BLUETOOTH_CLASS_DEVICE_MINOR_WEARABLE_HELMET: 0x04,
			BLUETOOTH_CLASS_DEVICE_MINOR_WEARABLE_GLASSES: 0x05,
			BLUETOOTH_CLASS_DEVICE_MINOR_TOY_ROBOT: 0x01,
			BLUETOOTH_CLASS_DEVICE_MINOR_TOY_VEHICLE: 0x02,
			BLUETOOTH_CLASS_DEVICE_MINOR_TOY_DOLL: 0x03,
			BLUETOOTH_CLASS_DEVICE_MINOR_TOY_CONTROLLER: 0x04,
			BLUETOOTH_CLASS_DEVICE_MINOR_TOY_GAME: 0x05,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_UNDEFINED: 0x00,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_BLOOD_PRESSURE_MONITOR: 0x01,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_THERMOMETER: 0x02,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_WEIGHING_SCALE: 0x03,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_GLUCOSE_METER: 0x04,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_PULSE_OXIMETER: 0x05,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_PULSE_RATE_MONITOR: 0x06,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_DATA_DISPLAY: 0x07,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_STEP_COUNTER: 0x08,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_BODY_COMPOSITION_ANALYZER: 0x09,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_PEAK_FLOW_MONITOR: 0x0a,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_MEDICATION_MONITOR: 0x0b,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_KNEE_PROSTHESIS: 0x0c,
			BLUETOOTH_CLASS_DEVICE_MINOR_HEALTH_ANKLE_PROSTHESIS: 0x0d,
			// from  BluetoothClassDeviceService of Tizen
			BLUETOOTH_CLASS_DEVICE_SERVICE_LIMITED_DISCOVERABILITY: 0x0001,
			BLUETOOTH_CLASS_DEVICE_SERVICE_POSITIONING: 0x0008,
			BLUETOOTH_CLASS_DEVICE_SERVICE_NETWORKING: 0x0010,
			BLUETOOTH_CLASS_DEVICE_SERVICE_RENDERING: 0x0020,
			BLUETOOTH_CLASS_DEVICE_SERVICE_CAPTURING: 0x0040,
			BLUETOOTH_CLASS_DEVICE_SERVICE_OBJECT_TRANSFER: 0x0080,
			BLUETOOTH_CLASS_DEVICE_SERVICE_AUDIO: 0x0100,
			BLUETOOTH_CLASS_DEVICE_SERVICE_TELEPHONY: 0x0200,
			BLUETOOTH_CLASS_DEVICE_SERVICE_INFORMATION: 0x0400
		}

	}, true);
});
